### ISSUE TITLE
Add automation HTML attributes to all Spark components

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#671] opened 2018-10-12 16:45 UTC
Add data-id="component" to Spark components. For example, for buttons, we would add data-id="button". 

We also need to add documentation that explains the convention devs should use when there is the case of more than one component being on the page. For example, if they have three buttons on the page, they should label them as data-id="button-1", data-id="button-2", data-id="button-3". This ensures they are all unique. 

- [x] Accordions
- [x] Alerts
- [x] Dividers
- [x] Footer
- [x] Icons
- [x] Inputs
- [x] Links
- [x] Lists
- [x] Masthead
- [x] Modals
- [x] Navigation
- [x] Pagination
- [x] Promo
- [x] Tables
- [x] Tabbed Nav
- [x] Toggle
- [x] Buttons
- [x] Awards
- [x] Cards
- [x] Dictionary
- [x] Highlight Board

**Comment by yodasw16** [comment] 2018-10-12 23:34
This is a duplicate of https://github.com/sparkdesignsystem/spark-design-system/issues/585. I'd like to break this out into separate issues and mark them all for hacktoberfest if possible. Just need one solid issue with all of the details and then I can create the others based off that.

**Comment by afebbraro** [comment] 2018-10-15 12:10
@yodasw16 Is there anything about this issue that you would like explained better?

**Comment by yodasw16** [comment] 2018-10-15 13:19
Where do you think the documentation needs to go for this? Is it someting that should be documented in ever component, or somewhere else?

**Comment by afebbraro** [comment] 2018-10-15 13:50
Documenting it in every component ensures that it won't be missed. It could be a "restriction". Something like "if you are using more than one of these then you need to follow ....."

**Comment by bobwise** [comment] 2018-11-01 20:59
- [x] Accordions
- [x] Alerts
- [x] Dividers
- [x] Footer
- [x] Icons
- [ ] Inputs
- [x] Links
- [ ] Lists
- [ ] Masthead
- [ ] Modals
- [ ] Navigation
- [ ] Pagination
- [x] Promo
- [ ] Tables
- [ ] Tabbed Nav
- [ ] Toggle
- [ ] Buttons
- [ ] Awards
- [ ] Cards
- [ ] Dictionary
- [ ] Highlight Board

**Comment by bobwise** [comment] 2018-11-08 21:36
Adding unit tests as a separate issue

**Closed by bobwise** 2018-11-08 21:36 UTC
Labels: scope: all pkgs, type: enhancement
